In [14]:
import gym
import random
import numpy as np

In [15]:
environment = gym.make('FrozenLake-v1',is_slippery =False,render_mode="ansi")
environment.reset()

nb_states = environment.observation_space.n #satırlar 16 tane
nb_actions = environment.action_space.n #sutunlar 4 tane

qtable = np.zeros((nb_states,nb_actions))
print("Q-table")
print(qtable)


Q-table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


render_mode----görselleştirme için gerekli
is_slippery----ajanın kaygan bir yüzeyde hareket ettiğini varsaymak

### sol:0,asagi:1,sag:2,yukari:3 ###

###

In [16]:
action = environment.action_space.sample()

new_state,reward,done,info, _= environment.step(action)

c:\Users\DeLL\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
